### ISSUE TITLE
specall missing a cvar

### ISSUE THREAD

**Issue by dsverdlo** [BarelyMiSSeD/minqlx-plugins#1]
Upon loading the specall plugin an error is shown in the console:

`File "./minqlx-plugins/specall.py", line 26, in __init__   
self.add_command(("specallversion", "specall_version"), self.specAll_version, int(self.get_cvar("qlx_protectAdminLevel")))`
 TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Whenever you want to use a cvar in a plugin, best to make sure it exists (with self.set_cvar_once)

You can't assume server owners will also install protect.py and that that plugin would be loaded before specall

With regards,
iou

**Comment by BarelyMiSSeD** [comment]
I will have to look at that. I was not intending to require any other
plugin to be loaded.

Thanks

**Comment by BarelyMiSSeD** [comment]
Updated the script.

**Comment by dsverdlo** [comment]
I heard it works, thanks :-)
