### ISSUE TITLE
wipedout

### ISSUE THREAD

**Issue by kikson112** [BarelyMiSSeD/minqlx-plugins#11]
hello

is this mod need factories ? i loaded it but nothik happend, i add also cvars but players doesnt haver anyy stuff.

**Comment by BarelyMiSSeD** [comment]
the wipeout factory you can use is on my github... that is how I would do it... but you don't have to do a factory if you really don't want to... a factory lets you callvote that factory in though and it will report to qlstats as a elo-b
Get tha factory in the ../scripts directory ... https://github.com/BarelyMiSSeD/minqlx-plugins/tree/master/scripts

**Comment by kikson112** [comment]
thank u for respond, so in fact wipeout need mappol for it ? i dont want use factories, i just want try wipeout, but when i load it nothink changed at all, now i try with ur mapppol

**Comment by kikson112** [comment]
sorry but still nothink, plugin load succes no any single error, but in game nothink hanged, cvars added to cfg

**Comment by BarelyMiSSeD** [comment]
If you are not going to use a factory then you need a cvar set in your server config
set qlx_wipeoutFactory "0"

**Comment by BarelyMiSSeD** [comment]
The instructions for all of the setup are at the top of the wipeout.py file

**Comment by kikson112** [comment]
i think i found a problem, game mode is playing CA, but when i check in game g_factory is ctf so probably this is a problem, bit wierd, mappool was ca, ok nvm, when i put in cfg g_factory CA i need set qlx_wipeoutFactory to 1 ? 

yes i readed it 20 times but my bad i never check g_factory

**Comment by kikson112** [comment]
works like a charm thank u!
