### ISSUE TITLE
Sounds cant be found?

### ISSUE THREAD

**Issue by WhereAreMyBulletsGoing** [BarelyMiSSeD/minqlx-plugins#12]
So i used your myFun.py script with all the sounds. I have chosen all sounds to be loaded so i pick "63" in the server.cfg and i went ingame to tryout the sounds and this is what i get

[https://i.ibb.co/B4CXhN9/20210309090603-1.jpg](https://i.ibb.co/B4CXhN9/20210309090603-1.jpg)

The workshop items has been downloaded although, so i dont know whats wrong..

**Comment by BarelyMiSSeD** [comment]
The server may not have downloaded the workshop or the client didn’t. The server usually is not able to download the workshop items during the startup process. It has to be done manually with the server not running.
