### ISSUE TITLE
Vote bans stored in redis db

### ISSUE THREAD

**Issue by Melodeiro** [BarelyMiSSeD/minqlx-plugins#2]
Hi!

Can you add a possibility to store all bans in the redis db, like other plugins does? Or at least cvar for using global voteban.txt for all servers which is located at main baseq3 where is mappools and other stuff.

First is much better IMO xD

**Comment by BarelyMiSSeD** [comment]
The script looks for the voteban file in whatever directory you have your fs_homepath set to. If all your servers are using the same fs_homepath setting then they will use the same voteban file.

I will look into implementing your idea as well. Hopefully it won't take too long.

**Comment by Melodeiro** [comment]
I guess, the same fs_homepath will cause problems with log files, thats why i using separate. Also access.txt will not work, because server writing data on map reload and multiple servers can override or vanish settings.

Nice to hear, thanks!

**Comment by BarelyMiSSeD** [comment]
I uploaded a new file with database support. Let me know if you see any issues. I did testing but not very extensive.
