### ISSUE TITLE
Exception when i trying to ban votes (redis)

### ISSUE THREAD

**Issue by Melodeiro** [BarelyMiSSeD/minqlx-plugins#3]
Minqlx logs:
http://pastebin.com/Cui5YLML
I didn't investigated too much, just tried to add str() to the first argument at 204 and 205 lines:

`banEnd = datetime.datetime.strptime(str(voteban_time), TIME_FORMAT)`

That way !banvote and !unbanvote visually working. Didn't tested, if its actually bans people, !vblist shows steamid of a banned person.

**Comment by Melodeiro** [comment]
Issue related to some of my servers (maybe 50% of them), while others are just working fine.

**Comment by BarelyMiSSeD** [comment]
I will look into this and get back to you. Hopefully in the next day or 2. Thanks.

**Comment by BarelyMiSSeD** [comment]
All fixed. New version available.
