### ISSUE TITLE
!listvoteban shows an empty list (redis)

### ISSUE THREAD

**Issue by Melodeiro** [BarelyMiSSeD/minqlx-plugins#4]
I see an empty list, there is some people in !vblist output. Nothing special in logs.

One suspicious thing i saw, is that at first its showed 1 guy, who i just banned (there should be 3 persons tho) then at the next day, its empty. On another server !listvoteban showed an empty list right after adding new guy (after adding str() to the code: #3)

**Comment by Melodeiro** [comment]
Just checked if !voteban throws an exception from #3 on first server (where its worked yesterday) and now its throws the same. So this issue might be related to a the same issue with datatime, just i don't see any errors, because it happens somewhere where it will not write it into logs. In a function maybe.

**Comment by BarelyMiSSeD** [comment]
I will look into the code and get back to you.

Are you sure the bans had not expired?

**Comment by Melodeiro** [comment]
If i remember correctly, 2 old bans should be permanent (couple of years). New ban i just made was for 60 days, and it disappeared on first server immediately, on second server after 1 day.

**Comment by BarelyMiSSeD** [comment]
I have a fix to test that I should get to testing later today. If you would like to test it I have attached it here.
[voteban.txt](https://github.com/BarelyMiSSeD/minqlx-plugins/files/555555/voteban.txt)

Just change the .txt file extension to .py if you want to test it and get back to me.

**Comment by Melodeiro** [comment]
There is a typo at line 381:
`playerName = self.db.lindex(PLAYER_KEY.format(steam_id), 0)`
I have changed "steam_id" to "id", and its working fine now. All old bans showed in !listbanvote output.

I see now you are searching through all database instead of showing connected players. This was seems more reasonable. I remember, that i saw banned guy in output, when he was online. Its now followed by a 1-2 seconds freeze, and looks like, that its a server-side. Perhaps self.db.scan_iter should be done in a thread? I see, that kanzo made his [checkplayers.py](https://github.com/cstewart90/minqlx-plugins/blob/master/checkplayers.py#L47) that way.

**Comment by Melodeiro** [comment]
I guess its better to avoid using of self.players() then (at 379-382 lines), because its something, which can go wrong in a thread since that code will be running in a multiple game frames. Or to use it somewhere out of the thread

**Comment by BarelyMiSSeD** [comment]
I like the thread idea. I was worried about server lag when editing this this morning. Here is another file, if you want to test it.
[voteban.txt](https://github.com/BarelyMiSSeD/minqlx-plugins/files/556121/voteban.txt)

Hopefully this works. If not, I will just use the latest name stored in the redis database. I just like the idea of it matching the connected player, in case they change their name after connecting.

**Comment by Melodeiro** [comment]
I guess for proper handling the situation with threads, you just need now to add @minqlx.next_frame:

``` Python
@minqlx.next_frame
def check_conected_name(self, id):
        player_list = self.players()
        for p in player_list:
            if int(id) == p.steam_id:
                playerName = p.name
                break

        if playerName:
            return playerName
        else:
            return None
```

That way it should execute all whole function in a single frame like all default code and self.players() will not change during execution. Will test your version tommorow.

**Comment by BarelyMiSSeD** [comment]
all Fixed, Nwe version available

**Comment by Melodeiro** [comment]
Thanks for the fixes!
