### ISSUE TITLE
voteban.py bug

### ISSUE THREAD

**Issue by Melodeiro** [BarelyMiSSeD/minqlx-plugins#6]
Looks like, that after !voteban command, it doesn't adding the guy to the self.voteban, checked with !vblist command. After reloading the plugin, everything is working. Im using the redis database.

**Comment by BarelyMiSSeD** [comment]
Sorry it took so long to respond, I have been very busy. Are you still having any trouble with the script?

**Comment by Melodeiro** [comment]
Yes, i do. But the problem is a low-prioritized, so take your time.

**Comment by jwinett** [comment]
Did you set qlx_votebanRedisStorage to 1?

**Comment by Melodeiro** [comment]
Yes, i did.

**Comment by jwinett** [comment]
It was just a sort of hail-Mary I thought of while reading the code.  But, the code uses the same syntax to add the new ban to self.voteban whether using the file or Redis, so no low-hanging-fruit-glory for the spider.

**Comment by jwinett** [comment]
I just tested it on my server and it works with either qlx_votebanRedisStorage "0" or "1" ... weird

**Comment by Melodeiro** [comment]
Lol, checked again and now it works, strange... When i created that ticket, i remember, i had the latest 1.11 version. Also didn't any updates for sure. I guess i will have to close the ticket then. Checked the code too, looks ok.

**Comment by BarelyMiSSeD** [comment]
I am glad it is working. Let me know if there are any more issues... And it is supposed to work the same with both the database or the text file storage selected with the qlx_votebanRedisStorage switch.
