### ISSUE TITLE
running !listmaps lags whole server when run

### ISSUE THREAD

**Issue by roasticle** [BarelyMiSSeD/minqlx-plugins#7]
I think ideally the map list should be generated when the plugin first loads instead of every time !listmaps is called since there is significant yellow lagometer blocks when it is called and almost a connection interrupt.
You could load it into memory so that it won't lag every time the command is called. Good plugin idea though! :)

**Comment by BarelyMiSSeD** [comment]
The list is not gotten when !listmaps is called. It is done when the server is started or the script is loaded. The list is shown to the person who calls it when the command is issued. I use this on a bunch of servers without lag issues. What version do you have that is causing lag?  Some very early versions caused lag.

**Comment by roasticle** [comment]
Oh maybe it’s just the receiving client getting the lag spike then, assuming it was the server.

**Comment by BarelyMiSSeD** [comment]
Ah yes. The receiving client will get a little lag, it is unavoidable. But since this was designed to be viewed in the console it should be okay. Hope it works for you.
