### ISSUE TITLE
Vote bans works only from admin panel

### ISSUE THREAD

**Issue by Melodeiro** [BarelyMiSSeD/minqlx-plugins#8]
Hello.
Figured out, why its not worked sometimes for me. When its called from /callvote or /cv, i see only vote_started calls in minqlx logs. There is no vote_called, so the plugin can't cancel it. I have zmq fully enabled, any ideas why it doesn't want to work?

**Comment by Melodeiro** [comment]
Oh boy, tested it again, and now its working.. The only thing that changed was a daily server restart

**Comment by BarelyMiSSeD** [comment]
Glad you got it working. For some reason I missed the issue being opened. Let me know if you have any more trouble.
