### ISSUE TITLE
Typecast issue

### ISSUE THREAD

**Issue by li-nt** [BarelyMiSSeD/minqlx-plugins#9]
I inserted a check after line 305 due to a typecast error of some invalid value being returned.  

This is because the bdm:ft:games_completed and bdm:ft:games_left keys are not storing into redis for me.  I setup a second server and installed everything with default settings to see if it was my server, but the key values are still missing.  It may be a freezetag gametype issue.  The odd part is that values are being stored into the bdm:ft:rating key just fine.

_ERROR:_
(16:39:30) [ERROR @ minqlx.serverBDM.log_exception] TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

_FIX:_
try:
      games_left = self.get_db_field(player, "minqlx:players:{}:games_left")
       **if games_left is None:
       games_left = 0**

**Comment by BarelyMiSSeD** [comment]
I just put up a new one that should work. I am not in a position to test it though. Let me know.
